# Generated by Django 3.0.7 on 2020-07-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_name', models.CharField(max_length=50)),
                ('Prod_desc', models.CharField(max_length=300)),
                ('Pub_date', models.DateTimeField()),
            ],
        ),
    ]
