# Generated by Django 3.0.7 on 2020-07-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Prod_desc',
            new_name='Product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Prod_name',
            new_name='Product_name',
        ),
    ]
