# Generated by Django 3.0.7 on 2020-07-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200713_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
