# Generated by Django 3.0.7 on 2020-07-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Itemjson', models.CharField(max_length=5000)),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('Zip_code', models.CharField(max_length=500)),
            ],
        ),
    ]
