# Generated by Django 3.0.7 on 2020-07-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_updateorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateorder',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
